theme: jekyll-theme-slate
title: Welcome to my challenge project: Currency Converter home page!
description: Ghada Farrag: My #7DaysofCodeChallenge ALCwith Google - Mobile Web Specialist Track - June 2018
