theme: jekyll-theme-slate
title: "Welcome to my Currency Converter!"
description: "This is my code challenge project #7DaysofCodeChallenge - ALCwithGoogle - Mobile Web Specialist Track - June 2018 - By Ghada Farrag"
