theme: jekyll-theme-tactile
title: Welcome to my challenge project [Currency Converter] home page! - Ghada Farrag
description: Ghada Farrag's #7DaysofCodeChallenge ALCwith Google - Mobile Web Specialist Track - June 2018
