theme: jekyll-theme-modernist
title: "Welcome to Ghada Farrag's challenge project [Currency Converter]!"
description: "This is my code challenge project #7DaysofCodeChallenge - ALCwithGoogle - Mobile Web Specialist Track - June 2018"
