theme: jekyll-theme-slate
title: "Welcome to Ghada Farrag's challenge project [Currency Converter] home page!"
description: "This is my #7DaysofCodeChallenge - ALCwithGoogle - Mobile Web Specialist Track - June 2018"
